language: ruby
rvm:
  - 2.1

branches:
  only:
    - master
    - gh-pages

cache:
  bundler: true
  yarn: true
  directories:
    - "node_modules"

before_script:
  - bundle install
  - nvm install stable
  - node -v
  - npm install -g npm yarn
  - yarn install

script:
  - yarn build
  - bundle exec jekyll build
  - yarn sw

deploy:
  provider: pages
  skip_cleanup: false
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: _site
