language: ruby
rvm:
  - 2.1

branches:
  only:
    - master
    - gh-pages

cache:
  bundler: true
  yarn: true
  directories:
    - "node_modules"

before_script:
  - nvm -v
  - nvm install stable
  - node -v
  - npm install npm -g
  - yarn install

script: "yarn build"

deploy:
  provider: pages
  skip_cleanup: false
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: _site
