# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Growth Tools
email: contato@fundamental.digital
description: "Curadoria de recursos para fazer sua empresa crescer."

url: "https://ferramentas.digital"
baseurl: ""
permalink: /:title/
paginate: 20
paginate_path: "/p/:num"
domain_name: ferramentas.digital
ga_ua: UA-51117727-31

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

collections:
  categories:
    output: true
    permalink: /categoria/:title/

exclude:
  - Gemfile
  - GemfileTravis
  - cibuild.sh
  - Gemfile.lock
  - vendor
  - node_modules
  - yarn.lock
  - README.md
  - package.json
  - gulpfile.js
  - config.js
  - public/
  - html/
  - src/
